### ISSUE TITLE
Proposal: Data Description 

### ISSUE THREAD

**Issue by samson-bakos** [UBC-MDS/MacroView#7]

**Comment by J99thoms** [comment]
"In your proposal, briefly describe the dataset and the variables that you will visualize. If you are planning to visualize a lot of columns, provide a high-level descriptor of the variable types rather than listing every single column. For example, indicate that the dataset contains a variety of categorical variables for demographics and provide a brief list rather than describing every single variable. You may also want to consider visualizing a smaller set of variables given the short duration of this project. This might include brief exploratory data analysis for you to grasp what could be interesting aspects to look at in your data. We will not be grading the EDA aspect, but feel free to include your EDA notebooks in the public GitHub repo, so that you have everything in one place."
