### ISSUE TITLE
Sketch/ ReadMe

### ISSUE THREAD

**Issue by samson-bakos** [UBC-MDS/MacroView#9]

**Comment by J99thoms** [comment]
"Building from your research questions and usage scenarios, give a high-level description of the interface for the app you will build. Remember to be realistic about your expectations and plans since you will actually be implementing this app (but again, you will not be penalized if you need to adjust a bit in later milestones). It is better to design a slightly more limited app that you have time to implement well, instead of a complicated app that you don’t have time to finish. At the same time, you cannot just make a single bar chart and call it a day. The app needs to have a few plot panels. Use the visualizations from previous students shown in lecture 1 as a guide of complexity target for the final app.

In this description, you are not required to use specific terminology (i.e. widgets, components, etc…) or make reference to specific libraries. Your sketch can be hand-drawn or mocked up using a graphics editor. If you can show the app's visual design & interaction design in a single image that is ideal, but if you need more space to show some other planned features of your app you can include max three images for this proposal.

The description should be about 200-300 words and live in the README.md file of your GitHub.com repository. The sketch should be linked in the README.md file of your GitHub.com repository underneath the high-level description so that the image shows up on GitHub."
